# Base image
FROM my_odoo17_image_tag:17

# Switch to root user to perform administrative tasks
USER root

# Define environment variables
ARG PUID=1001
ARG PGID=997

# Create group and user with the specified UID and GID
RUN groupadd -g ${PGID} test1 && \
    useradd -u ${PUID} -g test1 -m test1

# Set environment variables
ENV PUID=${PUID} PGID=${PGID}

# Create /etc/odooscript
RUN mkdir -p /etc/odoo

# Copy entrypoint script and Odoo configuration file
COPY ./entrypoint.sh /
COPY ./odoo.conf /etc/odoo/

# Set permissions and Mount /var/lib/odoo to allow restoring filestore and /mnt/extra-addons for users addons
RUN chown test1 /etc/odoo/odoo.conf \
    && mkdir -p /mnt/extra-addons \
    && chown -R test1 /mnt/extra-addons \
    && chown -R test1 /var/lib/odoo \
    && chown -R test1 /etc/odoo \
    && chown -R test1 /entrypoint.sh
VOLUME ["/var/lib/odoo", "/mnt/extra-addons"]

# Expose Odoo services
EXPOSE 8069 8071 8072

# Set the default config file
ENV ODOO_RC=/etc/odoo/odoo.conf

COPY ./wait-for-psql.py /usr/local/bin/wait-for-psql.py

# Set permissions /usr/local/bin/wait-for-psql.py
RUN chown test1 /usr/local/bin/wait-for-psql.py

# Switch to this user
USER test1

# Continue with any additional configuration if needed
# Install Python packages in the virtual environment
# RUN pip install python-barcode	 # Already Install in the Origin Image